export const CATEGORY_TITLES = {
    base: "QUAL ROSTO TE REPRESENTA MELHOR?",
    clothing: "SUA ROUPA TAMBÉM DEMONSTRA SUA PERSONALIDADE!",
    eyes: "SEUS OLHOS SÃO A JANELA DO SEU CORAÇÃO!",
    eyebrows: "SUAS SOBRANCELHAS EXPRESSAM SEU OLHAR!",
    nose: "SEU NARIZ É A PONTA DE SEU SONHO!",
    mouth: "E ESSA BOCA HEIN... COMO FICARÁ?",
    hair: "SEU CABELO DECLARA QUEM VOCÊ É!",
    glasses: "VOCÊ VAI QUERER USAR ALGUM ACESSÓRIO?"
};